apiVersion: v1
kind: ConfigMap
metadata:
  name: kappnav.actions.service.app
data:
  url-actions: |
    [
      { 
        "name":"api-spec", 
        "text":"View OpenAPI Spec", 
        "text.nls":"View OpenAPI Spec",
        "description":"View OpenAPI Spec",  
        "description.nls":"View OpenAPI Spec", 
        "url-pattern":"http://localhost:${func.kubectlGet(service,${resource.$.metadata.name},--namespace,${resource.$.metadata.namespace},-o,jsonpath=${snippet.nodeport()})}/openapi/ui",
        "open-window": "tab", 
        "menu-item": "true"
      },
      {
        "name":"liveness",
        "text":"View Liveness Endpoint",
        "text.nls":"View Liveness Endpoint",
        "description":"View Liveness Endpoint",
        "description.nls":"View Liveness Endpoint",
        "url-pattern":"http://localhost:${func.kubectlGet(service,${resource.$.metadata.name},--namespace,${resource.$.metadata.namespace},-o,jsonpath=${snippet.nodeport()})}/live",
        "open-window": "tab",
        "menu-item": "true"
      }
    ]
  snippets: |
    {
      "nodeport": "function nodeport() {
        return '{.spec.ports[0].nodePort}'
      }"
    }
